### ISSUE TITLE
Full Stack projektin katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [jalho/j3.re_frontend#49]
# Katselmointi

Terve @jalho! Tässä lyhyt katselmointi Full Stack kurssin projektistasi.

### Mitä tein?

Selasin portfolion läpi.

### Kokemus

- Selkeä ja tyylikäs käyttöliittymä, joka menee siisti kasaan myös kapeammilla näytöillä. Hyvää työtä! 🥇
- Sivulta toiselle siirtyminen toimii sulavasti, ei turhaa odottelua.

## Koodi

- Frontend-puolen koodi on selkeästi organisoitua, hyvä!
- Tyylejä on määritelty modulaarisesti ja SASS-muuttujia on käytetty ulkoasun parametrisoinniksi, hienoa! Suosittelen tutustumaan vielä [css-moduuleihin](https://github.com/css-modules/css-modules), niin ei tarvitse murehtia globaalien valitsimien ongelmista. Toimii hyvin myös SASS:in kanssa. Myös "natiiveilla" [CSS-muuttujilla](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) alkaa olla aika hyvä selaintuki, joten niiden käyttöä voisi suositella. CSS-muuttujien etu SASS-muuttujiin nähtynä on se, että niitä voi muuttaa "ajonaikaisesti" JavaScriptillä, kun taas SASS-muuttujat määräytyvät sovelluksen rakentamisen yhteydessä.
- Komponenttien [lataaminen laiskasti](https://github.com/jalho/j3.re_frontend/blob/master/client/src/App.tsx#L37) on hyvä idea. Nopeuttaa isoissa sovelluksissa huomattavasti latauksia
- Reduxin actioneiden typet kannattaa tallentaa `const`-tyyppisiin muuttujiin ja käyttää niiden arvoja sen sijaan, että käyttää niitä merkkijonomuotoisena. Tämä ehkäisee kirjoitusvirheistä syntyviä bugeja ja helpottaa refaktorointia. Mallia voi katsoa Reduxin [dokumentaatiosta](https://redux.js.org/basics/actions)
- Syvien tietorakenteiden immutable päivittäminen Reduxin reducereissa puhtaalla JavaScriptilla on melko työlästä. [Immer](https://www.npmjs.com/package/immer)-kirjasto helpottaa tätä huomattavasti
- [Redux Toolkit](https://redux-toolkit.js.org/) tarjoaa todella hyviä työkaluja Reduxin käyttöön. Esim. [createReducer](https://redux-toolkit.js.org/usage/usage-with-typescript#createreducer)-funktio vähentää reducerien boilerplate koodia huomattavasti. Se käyttää sisäisesti Immer-kirjastoa, joten myös tilan päivittäminen helpottuu
- Myös backend-puolen koodi on selkeästi organisoitua, hienoa!
- GraphQL skeemaan liittyvä koodia on eriytetty järkevästi. Kun sovelluksen koko kasvaa, niin esim. [tämän](https://github.com/fullstack-hy2020/rate-repository-api/tree/master/src/graphql) tapaista, vielä hienojakoisempaa, organisointia voi harkita
- Kannattaa välttää nk. [Magic number](https://en.wikipedia.org/wiki/Magic_number_(programming)) arvoja, eli [esim. merkkijonoarvoja](https://github.com/jalho/j3.re_backend/blob/master/src/resolvers/index.ts#L257), joita käytetään suoraan koodissa vakiarvojen roolissa. Näistä seuraava usein bugeja typojen seurauksena ja ne vaikeuttavat refaktorointia. TypeScriptissä nämä kannattaa korvata [enumeilla](https://www.typescriptlang.org/docs/handbook/enums.html)

## Kokonaisuus

Päheä portfoliosivu, loistavalla domainilla. Sivun käyttöliittymä on selkeä ja sivujen välillä siirtyminen on sulaava. Sovelluksen koodi on kaikin puolin erittäin hyvin organisoitua, eikä laadullisesti ole suurempia ongelmia. Jos jatkossa toteutat staattisia sivuja, suosittelen tututustumaan myös [Gatsbyyn](https://www.gatsbyjs.com/).

**Comment by jalho** [comment]
Kiitos!
